apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test-nodejs
spec:
  inputs:
    resources:
      - name: git
        type: git
        targetPath: /
    params:
      - name: TARGET_DIRECTORY
        description: The subdirectory in which you want to execute the steps
        default: activity1
  steps:
    - name: install
      image: node
      workingDir: "/workspace/$(inputs.params.TARGET_DIRECTORY)"
      command: ["/bin/bash"]
      args:
        - -c
        - |
          echo 'Installing dependencies...'
          npm install
    - name: test
      image: node
      workingDir: "/workspace/$(inputs.params.TARGET_DIRECTORY)"
      command: ["/bin/bash"]
      args:
        - -c
        - |
          echo 'Unit Testing...'
          # npm run test:ci
