apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: dockerhub-bookinfo-details
spec:
  type: image
  params:
    - name: url
      value: index.docker.io/your-dockerhub-username/bookinfo
