apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: registry-bookinfo-details
spec:
  type: image
  params:
    - name: url
      value: de.icr.io/kmddk/<your-repository> # <your-repository> -> e.g. mn-bookinfo
