apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-nodejs
spec:
  selector:
    matchLabels:
      app: details-nodejs
  template:
    metadata:
      labels:
        app: details-nodejs
    spec:
      containers:
        - name: details-nodejs
          image: ibmgaragecph/bookinfo-v1:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: details
spec:
  selector:
    app: details-nodejs
  ports:
    - port: 80
      targetPort: 3000
